### ISSUE TITLE
Setup development environments

### ISSUE THREAD

**Issue by hachreak** [tiborsimko/invenio-devscripts#23]
I think that it's useful to have a script (or directly in kickstart) to setup the development environments (as specified in zenodo install instructions: https://github.com/bouzlibop/zenodo/blob/next/INSTALL.rst )

In particular: 

```bash
(invenio2)$ pip install -r requirements-dev.txt --exists-action i
(invenio2)$ cdvirtualenv src/invenio
(invenio2)$ kwalitee githooks install
```

Leo

**Comment by tiborsimko** [comment]
The devscripts are now merged in Invenio main repository for 1.0, 1.1, 1.2, legacy, master branches.
